### Module: NumPy Assignments
#### Lesson: NumPy
##### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [12]:
import numpy as np

In [13]:
arr = np.array([[1,2,3,4,5],[2,3,4,18,19],[5,6,7,19,1],[8,9,1,19,10],[18,9,1,10,2]])
print(arr.shape)
arr[0:,2] = 1
print(arr)

(5, 5)
[[ 1  2  1  4  5]
 [ 2  3  1 18 19]
 [ 5  6  1 19  1]
 [ 8  9  1 19 10]
 [18  9  1 10  2]]


In [14]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr1.shape)

print(np.eye(4))

(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [15]:
arr = np.random.randint(1,36, size = (6,6))
print(arr)

print(arr[2:5,1:4])


[[19 19  8 10 35 29]
 [ 3 26 16 20 27  8]
 [12 19 21 23 27 18]
 [29 26 11 14 13 29]
 [11 29 15 14 20 25]
 [28 18  7 14 24 12]]
[[19 21 23]
 [26 11 14]
 [29 15 14]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [16]:
arr = np.random.randint(1,100,size=(5,5))
print(arr)
#arr[:1],arr[-1:],arr[1:,0],arr[:,-1]
border_array = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_array)

[[76 64  4 80 16]
 [84 91 60 72 90]
 [26 88 74 73 24]
 [53 51 84 91 26]
 [41  6 73 86 50]]
[76 64  4 80 16 41  6 73 86 50 84 26 53 90 24 26]


#### Assignment 3: Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [17]:
arr1 = np.random.randint(1,25,size=(3,4))
arr2 = np.random.randint(1,25,size=(3,4))
print('arr1:\n',arr1)
print('arr2:\n',arr2)

#addition

print('addition:\n',arr1+arr2)

#subtraction
print('subtraction:\n',arr1-arr2)

#multiplication
print('multiplication\n',arr1*arr2)

#division
print('division:\n',arr1/arr2)

arr1:
 [[ 6  6  6 15]
 [ 8 24 23  9]
 [ 5 23 13  2]]
arr2:
 [[11  9  5 21]
 [21 22 22 22]
 [19 11 19 12]]
addition:
 [[17 15 11 36]
 [29 46 45 31]
 [24 34 32 14]]
subtraction:
 [[ -5  -3   1  -6]
 [-13   2   1 -13]
 [-14  12  -6 -10]]
multiplication
 [[ 66  54  30 315]
 [168 528 506 198]
 [ 95 253 247  24]]
division:
 [[0.54545455 0.66666667 1.2        0.71428571]
 [0.38095238 1.09090909 1.04545455 0.40909091]
 [0.26315789 2.09090909 0.68421053 0.16666667]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [29]:
arr = np.random.randint(1,10,size=(4,4))
print(arr)

#row wise
row_wise = np.sum(arr,axis=1)
print(f"row wise sum \n {row_wise}")

#column wise
column_wise = np.sum(arr,axis=0)
print(f"column wise sum \n {column_wise}")

[[8 8 4 7]
 [4 8 2 5]
 [8 3 2 6]
 [2 3 3 9]]
row wise sum 
 [27 19 19 17]
column wise sum 
 [22 22 11 27]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [37]:
arr4 = np.arange(1,26).reshape(5,5) # must match the elements so better use random int
print(arr4)

mean_value = print(f"mean:{np.mean(arr4)}")
median_value =  print(f"median:{np.median(arr4)}")
standard_deviation = print(f"standard deviation:{np.std(arr4)}")
variane_value = print(f"variance: {np.var(arr4)}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
mean:13.0
median:13.0
standard deviation:7.211102550927978
variance: 52.0


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [44]:
arr5 = np.random.randint(1,10,size = (3,3))
print(f"Original array: \n {arr5}")
mean_value = np.mean(arr5)
standard_deviation = np.std(arr5)
noralize_data = (arr5 - mean_value) / standard_deviation
print(noralize_data)

Original array: 
 [[7 1 8]
 [5 1 3]
 [3 5 8]]
[[ 0.94498092 -1.37451769  1.33156402]
 [ 0.17181471 -1.37451769 -0.60135149]
 [-0.60135149  0.17181471  1.33156402]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
arr_2d = np.random.randint(1,10,size=(3,3))
print(f"original array: \n {arr_2d}")
arr_1D = np.random.randint(1,10,size=(3,))
print(f"1D array is :\n {arr_1D}")

adding = arr_2d+arr_1D
print(f"Final Array:\n {adding}")

original array: 
 [[1 1 3]
 [3 3 5]
 [9 9 5]]
1D array is :
 [4 8 7]
Final Array:
 [[ 5  9 10]
 [ 7 11 12]
 [13 17 12]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.