In [8]:
import numpy as np

In [9]:
#Single array 1D
arr1 = np.array([1,2,3,45,])
print(arr1)
print(type(arr1)) 
print(arr1.shape) # (4,0) 4 rows and 0 columns

[ 1  2  3 45]
<class 'numpy.ndarray'>
(4,)


In [10]:
arr1.reshape(1,4)

array([[ 1,  2,  3, 45]])

In [11]:
#2D array 
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape) # one row 5 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [12]:
print(np.arange(0,10,2))
np.arange(0,10,2).reshape(5,1)


[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#identity matrix
np.eye(3) # prints all diagonals as 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of numpy and array

arr = np.array([[1,2,3],[4,5,6,]])
print(arr)
print(arr.shape)
print(arr.ndim) # dimention of array 2D,1D like that
print(arr.size) # size no of elements
print(arr.dtype) # based on system configuration
print(arr.itemsize) #item size in bytes

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [21]:
#numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print("addition: ",arr1+arr2)

#element wise substraction
print('substraction: ',arr1-arr2)

#element wise multiplication
print("multiplication: ",arr1*arr2)

#element wise division
print("division: ", arr1/arr2)

addition:  [11 22 33 44 55]
substraction:  [ -9 -18 -27 -36 -45]
multiplication:  [ 10  40  90 160 250]
division:  [0.1 0.1 0.1 0.1 0.1]


In [23]:
#Universal Functions

arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponensional
print(np.exp(arr))

#sin of array
print(np.sin(arr))

#log of array
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
# array slicing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
#how can we access 1 from 1st row
print(arr[0])
print(arr[0][0])

[1 2 3 4]
1


In [29]:
#how can we access 12 from row 3
print(arr[2][3])
print(arr[2,3])

12
12


In [31]:
# how can we access 7,8 from row 2 and 11,12 from row 3
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [ ]:
#replace values
arr[0,1] = 100
arr[1,3] = 80
print(arr)

[[  1 100   3   4]
 [  5   6   7  80]
 [  9  10  11  12]]


In [37]:
# statistical concepts - normalization
# to have a mean of 0 and stand deviation of 1

data = np.array([1,2,3,4,5])

#calculate mean
mean = np.mean(data)
#calculate standard deviation
std_dev = np.std(data)

#normalize the data

normalized_data = (data-mean)/std_dev
print('normalized data: ',normalized_data)


normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data = np.array([1,2,3,4,5,6,7,8,9])

#mean
mean = np.mean(data)
print('mean:',mean)

#median
median = np.median(data)
print('median:',median)

#Standar deviation
std_dev = np.std(data)
print("standard deviation:",std_dev)

#variance
variance = np.var(data)
print("Variance:",variance)

mean: 5.0
median: 5.0
standard deviation: 2.581988897471611
Variance: 6.666666666666667


In [43]:
#Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9])

print(data>5)
print(data<5)
print((data>=5) & (data<=8))

[False False False False False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False  True  True  True  True False]


In [45]:
print((data>5) | (data>10))

[False False False False False  True  True  True  True]
