### Module: NumPy Assignments
#### Lesson: NumPy
##### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [2]:
import numpy as np

In [29]:
#arr = np.array([[1,2,3,4,5],[2,3,4,18,19],[5,6,7,19,1],[8,9,1,19,10],[18,9,1,10,2]])
arr =np.random.randint(1,21, size=(5,5))
print(f'original array \n {arr}')
arr[0:,2] = 1
print(f'modified array \n {arr}')

original array 
 [[17 19 12  8  2]
 [ 2 10 10 16 16]
 [ 9  5  2 17  1]
 [15 12  8 17  3]
 [ 7  5  7  6 15]]
modified array 
 [[17 19  1  8  2]
 [ 2 10  1 16 16]
 [ 9  5  1 17  1]
 [15 12  1 17  3]
 [ 7  5  1  6 15]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [31]:
'''arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr1.shape)

print(np.eye(4))'''
arr = np.arange(1,17).reshape(4,4)
print(f"Original array \n {arr}")
np.fill_diagonal(arr,0)
print(f'modified array is \n {arr}')

Original array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
modified array is 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


##### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [5]:
arr = np.random.randint(1,36, size = (6,6))
print(arr)

print(arr[2:5,1:4])


[[26 19 28 23 29 22]
 [ 8  8  5 33 12  1]
 [29  9 29 27 12 19]
 [22 34 16 18  2 18]
 [12  8 25 15 20  5]
 [31 34  3 30 12 17]]
[[ 9 29 27]
 [34 16 18]
 [ 8 25 15]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)
#arr[:1],arr[-1:],arr[1:,0],arr[:,-1]
border_array = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_array)

[[92 66 39 56 90]
 [50 93 51 34 58]
 [35 93 60  8 96]
 [ 9 76 38 91 89]
 [41 50 73 57  2]]
[92 66 39 56 90 41 50 73 57  2 50 35  9 58 96 89]


#### Assignment 3: Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [7]:
arr1 = np.random.randint(1,25,size=(3,4))
arr2 = np.random.randint(1,25,size=(3,4))
print('arr1:\n',arr1)
print('arr2:\n',arr2)

#addition

print('addition:\n',arr1+arr2)

#subtraction
print('subtraction:\n',arr1-arr2)

#multiplication
print('multiplication\n',arr1*arr2)

#division
print('division:\n',arr1/arr2)

arr1:
 [[18  2 10 15]
 [16 12 21 11]
 [15 19 13 19]]
arr2:
 [[18 10 20 22]
 [12 15 22  8]
 [18 17 13 10]]
addition:
 [[36 12 30 37]
 [28 27 43 19]
 [33 36 26 29]]
subtraction:
 [[  0  -8 -10  -7]
 [  4  -3  -1   3]
 [ -3   2   0   9]]
multiplication
 [[324  20 200 330]
 [192 180 462  88]
 [270 323 169 190]]
division:
 [[1.         0.2        0.5        0.68181818]
 [1.33333333 0.8        0.95454545 1.375     ]
 [0.83333333 1.11764706 1.         1.9       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
arr = np.random.randint(1,16,size=(4,4))
print(arr)

#row wise
row_wise = np.sum(arr,axis=1)
print(f"row wise sum \n {row_wise}")

#column wise
column_wise = np.sum(arr,axis=0)
print(f"column wise sum \n {column_wise}")

[[2 2 5 4]
 [7 7 8 3]
 [4 5 3 8]
 [8 2 5 6]]
row wise sum 
 [13 25 20 21]
column wise sum 
 [21 16 21 21]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [34]:
arr4 = np.random.randint(1,21,size=(5,5)) # must match the elements so better use random int
print(arr4)

mean_value = print(f"mean:{np.mean(arr4)}")
median_value =  print(f"median:{np.median(arr4)}")
standard_deviation = print(f"standard deviation:{np.std(arr4)}")
variane_value = print(f"variance: {np.var(arr4)}")

[[19  1 16 18 10]
 [16  3 12  1 17]
 [16  5 14 14 15]
 [17  2 14  9 18]
 [ 4  8  2  7 10]]
mean:10.72
median:12.0
standard deviation:5.976754972390955
variance: 35.7216


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [10]:
arr5 = np.random.randint(1,10,size = (3,3))
print(f"Original array: \n {arr5}")
mean_value = np.mean(arr5)
standard_deviation = np.std(arr5)
noralize_data = (arr5 - mean_value) / standard_deviation
print(noralize_data)

Original array: 
 [[3 3 6]
 [9 6 8]
 [1 5 1]]
[[-0.61545745 -0.61545745  0.49236596]
 [ 1.60018938  0.49236596  1.23091491]
 [-1.3540064   0.12309149 -1.3540064 ]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [11]:
arr_2d = np.random.randint(1,10,size=(3,3))
print(f"original array: \n {arr_2d}")
arr_1D = np.random.randint(1,10,size=(3,))
print(f"1D array is :\n {arr_1D}")

adding = arr_2d+arr_1D
print(f"Final Array:\n {adding}")

original array: 
 [[4 3 9]
 [1 5 4]
 [3 4 7]]
1D array is :
 [4 6 9]
Final Array:
 [[ 8  9 18]
 [ 5 11 13]
 [ 7 10 16]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [35]:
arr_2D = np.random.randint(1,17,size = (4,4))
print(f'Original arr_2d: \n{arr_2D}')
arr_1D = np.random.randint(1,17,size=(4,))
print(f"Original arr_1D is \n {arr_1D}")

sub = arr_2D - arr_1D[:, np.newaxis]
print(f'subtractng result:\n {sub}')

Original arr_2d: 
[[11  7 12  3]
 [ 8 14  8  7]
 [ 3  1  2  5]
 [ 3  7 13  7]]
Original arr_1D is 
 [ 9  3  8 13]
subtractng result:
 [[  2  -2   3  -6]
 [  5  11   5   4]
 [ -5  -7  -6  -3]
 [-10  -6   0  -6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [40]:
matrix = np.random.randint(1,11,size=(3,3))
print(f"Original matrix is \n {matrix}")

# compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant: ", determinant)

# compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse Matrix: \n",inverse)

# compute the eigenvalues
eigenValues = np.linalg.eigvals(matrix)
print("EigeValues:\n ",eigenValues)

Original matrix is 
 [[3 8 5]
 [7 6 5]
 [3 2 7]]
Determinant:  -195.99999999999991
Inverse Matrix: 
 [[-0.16326531  0.23469388 -0.05102041]
 [ 0.17346939 -0.03061224 -0.10204082]
 [ 0.02040816 -0.09183673  0.19387755]]
EigeValues:
  [15.14555151 -3.19542867  4.04987716]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [41]:
array1 = np.random.randint(1,11, size=(2,3))
array2 = np.random.randint(1,11, size=(3,2))
print("Array 1: \n",array1)
print("Array 2: \n ",array2)

# perform matrix multiplication
result = np.dot(array1,array2)
print("Matrix Multiplication result: \n",result)

Array 1: 
 [[7 1 2]
 [7 9 7]]
Array 2: 
  [[ 9  1]
 [ 7 10]
 [ 8  4]]
Matrix Multiplication result: 
 [[ 86  25]
 [182 125]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [13]:
arrShape3 = np.random.randint(1,10, size =(3,3))
print(arrShape3)
arrshape1to9=arrShape3.reshape(1,9)
print(arrshape1to9)

print(arrshape1to9.reshape(9,1))



[[2 3 8]
 [2 7 6]
 [1 6 9]]
[[2 3 8 2 7 6 1 6 9]]
[[2]
 [3]
 [8]
 [2]
 [7]
 [6]
 [1]
 [6]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [42]:
arrs = np.random.randint(1,25,size=(5,5))
print(f"original array :\n {arrs}")

flattenarr = arrs.flatten()
print(f'flatten array : \n {flattenarr}')

againReshape = flattenarr.reshape(5,5)
print(f"Again reshape to original : \n {againReshape}")



original array :
 [[ 2 18 24 13 16]
 [12 17 20 15  3]
 [ 3 20  6 17  3]
 [23 12  6  3 23]
 [ 9 18 21 10 10]]
flatten array : 
 [ 2 18 24 13 16 12 17 20 15  3  3 20  6 17  3 23 12  6  3 23  9 18 21 10
 10]
Again reshape to original : 
 [[ 2 18 24 13 16]
 [12 17 20 15  3]
 [ 3 20  6 17  3]
 [23 12  6  3 23]
 [ 9 18 21 10 10]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [43]:
array = np.random.randint(1,21, size=(5,5))
print(f"original array:")
print(array)

# using fancy indexing to extract the elements at the corners of the array
corners = array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corners Elements: " , corners)

original array:
[[ 9 12 12  6  9]
 [16 18  4  3 17]
 [ 3  7  8  8 13]
 [ 6  3 16 18 18]
 [ 1 13  9  7  5]]
Corners Elements:  [9 9 1 5]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.